/**
 * @file branding.ts
 * @module config
 * @description Branding configuration for PDF exports including company name, logo, watermarks, and footer text
 * @author BharatERP
 * @created 2025-01-27
 */

/**
 * Branding configuration interface
 */
export interface BrandingConfig {
  companyName: string;
  companyLogoUrl?: string;
  watermarkText?: string;
  footerText?: string;
  copyrightText?: string;
}

/**
 * Get branding configuration from environment variables or defaults
 */
export function getBrandingConfig(): BrandingConfig {
  return {
    companyName: process.env.PDF_COMPANY_NAME || "BharatERP",
    companyLogoUrl: process.env.PDF_COMPANY_LOGO_URL,
    watermarkText: process.env.PDF_WATERMARK_TEXT || "CONFIDENTIAL",
    footerText: process.env.PDF_FOOTER_TEXT || "Generated by BharatERP Construction Report System",
    copyrightText: process.env.PDF_COPYRIGHT_TEXT || `© ${new Date().getFullYear()} BharatERP. All rights reserved.`
  };
}

/**
 * Get default branding configuration
 */
export function getDefaultBranding(): BrandingConfig {
  return {
    companyName: "BharatERP",
    watermarkText: "CONFIDENTIAL",
    footerText: "Generated by BharatERP Construction Report System",
    copyrightText: `© ${new Date().getFullYear()} BharatERP. All rights reserved.`
  };
}

